using System.Security.Cryptography;

/* The code is defining a namespace called `SecureRandomNamespace` and within that namespace, there is
a class called `SecureRandom`. */
namespace SecureRandomNamespace
{
    /* The SecureRandom class generates random bytes using a secure random number generator. */
    public class SecureRandom
    {
        private RandomNumberGenerator rng = RandomNumberGenerator.Create();

        /// <summary>
        /// The NextBytes function generates random bytes and stores them in the provided byte array.
        /// </summary>
        /// <param name="bytes">The "bytes" parameter is an array of bytes that will be filled with random
        /// values generated by the "rng" object.</param>
        public void NextBytes(byte[] bytes)
        {
            rng.GetBytes(bytes);
        }
    }
}
